export const optionTypeList = [
  { value: "STRING", label: "Строка" },
  { value: "INTEGER", label: "Целочисленное" },
  { value: "DOUBLE", label: "Вещественное" },
  { value: "BOOLEAN", label: "Правда или ложь" },
  { value: "DATE", label: "Дата" },
];

export const optionMeasureList = [
  { value: "METERS", label: "Метры" },
  { value: "CENTIMETERS", label: "Сантиметры" },
  { value: "MILLIMETERS", label: "Миллиметры" },
  { value: "SQUARE_METERS", label: "Квадратные метры" },
  { value: "SQUARE_CENTIMETERS", label: "Квадратные сантиметры" },
  { value: "SQUARE_MILLIMETERS", label: "Квадратные миллиметры" },
  { value: "KILOGRAMS", label: "Килограммы" },
  { value: "LITERS", label: "Литры" },
  { value: "MILLILITERS", label: "Миллилитры" },
  { value: "KILOGRAMS_METER_CUBE", label: "Килограммы на кубический метр" },
  { value: "GRAMS_CENTIMETER_CUBE", label: "Граммы на кубический сантиметр" },
  { value: "PIECES", label: "Штуки" },
  { value: "ROLLS", label: "Рулоны" },
  { value: "SHEETS", label: "Листы" },
  { value: "WATTS", label: "Ватты" },
  { value: "VOLTS", label: "Вольты" },
  { value: "AMPERES", label: "Амперы" },
  { value: "OHMS", label: "Омы" },
  { value: "BUNDLES", label: "Пучки" },
  { value: "PACKS", label: "Пакеты" },
  { value: "OTHER", label: "Другое" },
];
